### ISSUE TITLE
Maintaining a consistent file type 

### ISSUE THREAD

**Issue by akyag** [adamjakab/BeetsPluginGoingRunning#13]
I currently convert songs using the convert plugin and use some tags to export songs for my Walkman device, since it can only play mp3s. Is something like this possible when you export the files? maybe setting up a bit-rate and file type and convert files which aren't mp3s? Just a suggestion :)
Thanks a lot for this! Never thought we could use bpm like this :+1:

**Comment by adamjakab** [comment]
Hi @akyag! Are you asking if a audio file conversion will be included in this plugin in the future?

**Comment by akyag** [comment]
Yes! :)

**Comment by adamjakab** [comment]
No, that is out of the scope of this plugin. You will have to continue to convert your files with the `convert` plugin and then use this one to make the selection and copy the files to an external player.
