### ISSUE TITLE
Add tags to repository

### ISSUE THREAD

**Issue by daniele-athome** [adamjakab/BeetsPluginGoingRunning#31]
Congrats on this plugin! I'm considering it for generating sport routine playlists.
Not really a bug or something, just here to recommend adding tags to this repository for improved visibility/reachability in GitHub (personally I like to go to [this page](https://github.com/topics/beets-plugin) periodically to see if new plugins appear).
I've seen beets plugins repos usually having these tags:

- beets
- beets-plugin

**Comment by adamjakab** [comment]
Done. Thanks for the tip.
